/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bar: typeof import('./components/user/Bar.vue')['default']
    BarInfoCard: typeof import('./components/user/BarInfoCard.vue')['default']
    Container: typeof import('./components/common/Container.vue')['default']
    Drawer: typeof import('./components/layout/Drawer.vue')['default']
    ImageViewer: typeof import('./components/common/ImageViewer.vue')['default']
    Item: typeof import('./components/common/Item.vue')['default']
    Loading: typeof import('./components/common/Loading.vue')['default']
    LoadingWithTip: typeof import('./components/notification/LoadingWithTip.vue')['default']
    Notification: typeof import('./components/notification/Notification.vue')['default']
    NotificationBox: typeof import('./components/notification/NotificationBox.vue')['default']
    PageState: typeof import('./components/common/PageState.vue')['default']
    PinnedThread: typeof import('./components/thread/PinnedThread.vue')['default']
    QRLoginPanel: typeof import('./components/user/QRLoginPanel.vue')['default']
    Reply: typeof import('./components/thread/Reply.vue')['default']
    RippleButton: typeof import('./components/common/RippleButton.vue')['default']
    RippleButtonWithIcon: typeof import('./components/common/RippleButtonWithIcon.vue')['default']
    SubPost: typeof import('./components/thread/SubPost.vue')['default']
    SubPostView: typeof import('./components/thread/SubPostView.vue')['default']
    TabInfo: typeof import('./components/layout/TabInfo.vue')['default']
    TabList: typeof import('./components/layout/TabList.vue')['default']
    Tabs: typeof import('./components/layout/Tabs.vue')['default']
    Tag: typeof import('./components/common/Tag.vue')['default']
    Thread: typeof import('./components/thread/Thread.vue')['default']
    ThreadLite: typeof import('./components/thread/ThreadLite.vue')['default']
    Tip: typeof import('./components/notification/Tip.vue')['default']
    TitleBar: typeof import('./components/layout/TitleBar.vue')['default']
    Toast: typeof import('./components/common/Toast.vue')['default']
    UserManageCard: typeof import('./components/user/UserManageCard.vue')['default']
    UserReply: typeof import('./components/reply/UserReply.vue')['default']
    UserReplyContentDisplay: typeof import('./components/reply/UserReplyContentDisplay.vue')['default']
  }
}
